baseurl = "http://satta.me"
DefaultContentLanguage = "en"
title = "Satta Ravi"
theme = "beautifulhugo"
metaDataFormat = "yaml"
#pygmentsUseClasses = true
#pygmentCodeFences = true
disqusShortname = "satta-me"
googleAnalytics = "UA-101747393-1"

[Params]
  subtitle = "Aspiring Data Scientist | Full Stack Engineer"
  logo = "img/satta.jpg"
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  rss = true
  comments = true
#  commit = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

[Author]
  name = "Satta Ravi"
  github = "sattaravi"
  twitter = "sattaravi"
  linkedin = "satta"
  stackoverflow = "users/2167830/satta-ravi" 
  instagram = "satta.me"

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3

