name = "Minimat"
license = "Apache 2.0"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE.md"
description = "Minimal Material Theme"
homepage = "http://siteforthistheme.com/"
tags = ["blog"]
features = ["blog"]
min_version = "0.21"

[author]
  name = "Satta Ravi"
  homepage = "https://satta.me"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
